### ISSUE TITLE
breadcrumbs not rended when PK is in url

### ISSUE THREAD

**Issue by soulraven** [idlesign/django-sitetree#192] opened 2016-02-06 14:39 UTC
i have try to render some breadcrumbs but when the url contains a PK is not rended anymore like:

```
url(r'^address/(?P<pk>\d+)/$', UserProfileUpdateAddress.as_view(), name="address_edit"),
url(r'^address/(?P<pk>\d+)/delete/$', UserProfileDeleteAddress.as_view(), name="address_delete"),
```

 and i have try like this for the url in sitetree:
userProfile:address_edit address.id

is not working? i am doing something wrong?

**Comment by soulraven** [comment] 2016-02-06 16:45
L.E. try also with:
userProfile:address_edit pk

still nothing....

**Comment by idlesign** [comment] 2016-02-07 02:56
This won't budge `^address/(?P<pk>\d+)/$`, except `pk` is available as template context variable.
The same goes to `address.id` — please check that `address` object is passed into template.

**Comment by soulraven** [comment] 2016-02-07 06:35
The address object is not passed, is passed only the form object from the UpdateView.....

**Comment by idlesign** [comment] 2016-02-07 12:58
So you should pass it.

**Comment by soulraven** [comment] 2016-02-16 14:30
There is a problem when the menus contains multiple vars, like in my example, address.id company.id and so on
When a view is rended with a specific url format, the site tree try to resolve the address for all the menus present in the treeitem, and fills logs with errors,
``Exception while resolving variable 'address' in template 'company/company_update_form.html'.``

in this view where the error is raised the address var is not available, and is not necessary, but is present in treeitem for another menu

I guess is a problem that the vars are resolved even if the menus are not necessary for that url.

**Comment by idlesign** [comment] 2016-02-16 14:52
Please describe you menu, and show a context dict passed to template.

**Comment by soulraven** [comment] 2016-02-16 17:19
i have added printscreens with the menu structure, template vars that are not accessible and the excessive queries.

The problem is that even if a url is not pointing to a specific breadcrumb, sitetree try to resolve all the menus and all the url, even if the specific var is not present in the context of that view.
And the second problem is with excessive query generated by sitetree, and for this i don't have any explanation

![query](https://cloud.githubusercontent.com/assets/1303303/13084324/a96c3f76-d4e1-11e5-9866-f790b8308e41.jpg)
![sitetree](https://cloud.githubusercontent.com/assets/1303303/13084325/a971871a-d4e1-11e5-9134-4cb1bdc00517.jpg)
![template_vars](https://cloud.githubusercontent.com/assets/1303303/13084326/a9759c42-d4e1-11e5-9108-ac8aaaa8de9a.jpg)

**Comment by soulraven** [comment] 2016-02-16 17:27
with a simple view, and DB contains a single record i get 68 query by sitetree and 38 unresolved vars

`@method_decorator(login_required, name='dispatch')
class UserProfileListAddress(ListView):
	"""
	@resolve the theme file to userprofileaddress_list.html
	"""
	model = UserProfileAddress
	template_name = 'userProfile/userprofileaddress_list.html'

	def get_queryset(self):
		return UserProfileAddress.objects.filter(user_profile=self.request.user.profile)`

![extra_query](https://cloud.githubusercontent.com/assets/1303303/13084731/423eef04-d4e3-11e5-848d-8103f71b840b.jpg)

**Comment by idlesign** [comment] 2016-02-17 13:15
> if a url is not pointing to a specific breadcrumb, sitetree try to resolve all the menus and all the url,

So that's about breadcrumbs. This behavour is due to the fact that to have all the items in breadcrumbs functional you need to resolve URLs of every item. 

> excessive query generated by sitetree, and for this i don't have any explanation

I presume this screenshot is from `Editare banca`. Note that you defined URL pattern as `company:bank_update company.id bank.id`, I believe that `company.id` here is excessive, and `bank.id` should be just enough. That may be the source of queries.

> a single record i get 68 query by sitetree

What's in your `userProfile/userprofileaddress_list.html`?

**Comment by soulraven** [comment] 2016-02-17 13:55
`{% extends "../../dashboard_main/templates/tui2tone_bootstrap/fluid.html" %}
{% load i18n %}
{% load tz %}
{% load static from staticfiles %}
{% load tui2tone_bootstrap %}
{% load sitetree %}
{% load userProfile_extras %}

{% block breadcrumbs %}
    {% sitetree_breadcrumbs from "profile_menu" template "tui2tone_bootstrap/breadcrumbs/bootstrap3.html" %}
{% endblock %}

{% block sidebar_content %}
    {% sitetree_menu from "profile_menu" include "trunk" template "userProfile/fragments/sidebar_profile.html" %}
{% endblock %}

{% block content %}
    <div class="side-body">
            <div class="page-title">
                <span class="title">{% trans 'userProfileAddressList' %}</span>
                <div class="description">{% trans 'userProfileAddressListDescription' %}</div>
            </div>
            <div class="row">
                <div class="card">
                    <div class="card-body">
                    {% max_address_limit as address_limit %}
                    {% if object_list|length < address_limit %}
                        <div class="pull-right">
                            <a href="{% url "userProfile:address_create" %}" class="btn btn-primary">
                                {% trans 'userProfileAddressCreateBtn' %}
                            </a>
                        </div>
                    {% endif %}
                        <div class="clearfix"></div>
                        <table class="table table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>{% trans 'userProfileTableEditLabel' %}</th>
                                    <th>{% trans 'userProfileAddressFullTableLabel' %}</th>
                                    <th>{% trans 'userProfileTableModifiedLabel' %}</th>
                                    <th>{% trans 'userProfileTableDeleteLabel' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for address in object_list %}
                                <tr>
                                    <td>
                                        <a href="{%  url 'userProfile:address_edit' address.id %}" class="btn btn-success">
                                            {% trans 'userProfileTableEditButton' %}
                                        </a>
                                    </td>
                                    <td>{{ address }}</td>
                                    <td>{{address.modified|localtime|short_datetime }}</td>
                                    <td>
                                        <a href="{% url 'userProfile:address_delete' address.id %}" class="btn btn-danger">
                                            {% trans 'userProfileTableDeleteButton' %}
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}`

**Comment by idlesign** [comment] 2016-02-17 14:43
Since those SQLs have LIMIT 21 it should be a hint that there is a problem somewhere in your queries. So it has nothing to with sitetree as it is.

You may be interested in reading the old discussion about 21 - https://groups.google.com/forum/#!topic/django-developers/PkzS9Wv6hIU/discussion

**Comment by soulraven** [comment] 2016-02-17 17:47
have a look a on my code...
i have put the code above

**Comment by idlesign** [comment] 2017-03-11 05:11
Is this issue still relevant as of 1.7.0 (with cache machinery reworked)?

**Comment by idlesign** [comment] 2017-04-06 16:49
Closing this one. 
Feel free to reopen if the issue is relevant for the latest version.

**Closed by idlesign** 2017-04-06 16:49 UTC
Labels: support
