### ISSUE TITLE
Cache invalidation not working in v1.6.0 but worked in v1.5.1, any clues?

### ISSUE THREAD

**Issue by simongartz** [idlesign/django-sitetree#218] opened 2016-11-17 15:10 UTC
Hi!

I was upgrading sitetree to v1.6.0 from v1.5.1 and was experiencing great speed up of the sitetree rendering.
Later when I tried to add an item in the admin interface it didn't show up even if I flushed Redis. It did show up after I restarted the servers (Heroku 14 dynos). Also the site showed different versions of the site tree randomly, it felt just like the cache now ended up in local memory even if the only change was upgrading sitetree, downgrading to v1.5.1 made it work as expected again.

So my question is if there are any new configuration requirements in the new 1.6.0 release?

We are running Django 1.8.4 python 2.7.11

**Comment by idlesign** [comment] 2016-11-17 15:26
Thank you for the report.

I'm currently working on a new test suite, some issues with caching are alredy spotted, and will be fixed. It will take some time though.

Do have any errors related to sitetree in logs?

**Comment by simongartz** [comment] 2016-11-18 08:10
During the short time we used the 1.6.0 release we didn't see any errors in the logs. Running with the old 1.5.1 release we do get quite many of the following error, I saw others reported similar errors for the 1.5.1 version or earlier.

```
Nov 18 08:55:24 the-web-app app/web.4:      return sitetree.children(self.tree_item, self.navigation_type, self.use_template.resolve(context), context) 
Nov 18 08:55:24 the-web-app app/web.4:    File "/app/.heroku/python/lib/python2.7/site-packages/sitetree/sitetreeapp.py", line 797, in children 
Nov 18 08:55:24 the-web-app app/web.4:      tree_items = self.filter_items(tree_items, navigation_type) 
Nov 18 08:55:24 the-web-app app/web.4:    File "/app/.heroku/python/lib/python2.7/site-packages/sitetree/sitetreeapp.py", line 829, in filter_items 
Nov 18 08:55:24 the-web-app app/web.4:      no_access = not self.check_access(item, self._global_context) 
Nov 18 08:55:24 the-web-app app/web.4:    File "/app/.heroku/python/lib/python2.7/site-packages/sitetree/sitetreeapp.py", line 740, in check_access 
Nov 18 08:55:24 the-web-app app/web.4:      authenticated = self._global_context['request'].user.is_authenticated() 
Nov 18 08:55:24 the-web-app app/web.4:    File "/app/.heroku/python/lib/python2.7/site-packages/django/template/context.py", line 71, in __getitem__ 
Nov 18 08:55:24 the-web-app app/web.4:      raise KeyError(key) 
Nov 18 08:55:24 the-web-app app/web.4:  KeyError: u'request' 
```

**Comment by idlesign** [comment] 2016-12-20 16:42
Meanwhile you may pull from https://github.com/idlesign/django-sitetree/tree/feat/major_refactoring branch to check cache invalidation if you will.

**Comment by idlesign** [comment] 2016-12-23 14:31
1.7.0 released, you may try it now.

**Comment by idlesign** [comment] 2017-04-06 16:52
Closing this one. 
Feel free to reopen if the issue is relevant for the latest version.

**Closed by idlesign** 2017-04-06 16:52 UTC
Labels: bug
